apiVersion: v1
kind: Service
metadata:
  name: dotnet-hello-world-service
  namespace: dotnet-hello-world
spec:
  selector:
    app: dotnet-hello-world
  type: LoadBalancer
  ports:
    - name: dotnet-hello-world-service
      protocol: TCP
      port: 80
      targetPort: 8080
